/**
 * Explicit database boundary for Ask Lifestyle Medicine and Faculty governance.
 *
 * This module intentionally imports schema definitions directly instead of
 * re-exporting the broad schema barrel. It is safe to import for schema tooling:
 * unlike `@workspace/db`, it does not create a connection or read environment
 * variables.
 *
 * Adding a table here is a boundary decision. Do not replace these named
 * exports with `export *`.
 */
import {
  facultyApplicationStatusEnum,
  facultyApplicationsTable,
  facultyInvitationStatusEnum,
  facultyInvitationsTable,
  facultyMembershipsTable,
  facultyRoleEnum,
  facultyUsersTable,
  institutionAgreementsTable,
  pillarsTable,
} from "./faculty";
import {
  sourceAssessmentStatusEnum,
  sourceAuditLogTable,
  sourceChunksTable,
  sourceKindEnum,
  sourceRetentionStatusEnum,
  sourceRightsBasisEnum,
  sourcesTable,
  sourceStatusEnum,
  sourceVersionsTable,
} from "./sources";
import {
  interpretationChunksTable,
  interpretationCommentsTable,
  interpretationOriginEnum,
  interpretationsTable,
  interpretationStatusEnum,
  interpretationVersionsTable,
  rubricCheckResultsTable,
  rubricChecksTable,
} from "./interpretations";
import {
  knowledgeRelationsTable,
  knowledgeRelationTypeEnum,
  knowledgeVersionChunksTable,
  knowledgeVersionChunkKindEnum,
  knowledgeVersionsTable,
} from "./knowledge";
import { agentQueriesTable, queryClustersTable } from "./agentQueries";
import { adviceGuardTermsTable } from "./adviceGuard";
import {
  crawlCandidateStatusEnum,
  crawlCandidatesTable,
  crawlRunStatusEnum,
  crawlRunsTable,
  researchDiscoveryCandidateStatusEnum,
  researchDiscoveryCandidatesTable,
  researchDiscoveryRunStatusEnum,
  researchDiscoveryRunsTable,
} from "./crawls";
import { gapDiscoveryEventsTable } from "./gapDiscovery";
import { consumerAccountsTable, consumerLoginTokensTable } from "./consumers";
import { emailRateLimitHitsTable } from "./emailRateLimit";
import { pillarResourcesTable } from "./pillarResources";
import { slmAnswerLinksTable } from "./slmAnswerLinks";
import {
  facultyVoiceProfilesTable,
  voiceProfileSourceEnum,
} from "./stewardVoice";
import { uncoveredEscalationsTable } from "./uncoveredEscalations";
import { visitorSessionsTable } from "./visitorSessions";
import {
  evalGradingsTable,
  evalItemsTable,
  evalRunsTable,
  expectedOutcomeEnum,
} from "./evals";

export {
  adviceGuardTermsTable,
  agentQueriesTable,
  consumerAccountsTable,
  consumerLoginTokensTable,
  crawlCandidateStatusEnum,
  crawlCandidatesTable,
  crawlRunStatusEnum,
  crawlRunsTable,
  evalGradingsTable,
  evalItemsTable,
  evalRunsTable,
  emailRateLimitHitsTable,
  expectedOutcomeEnum,
  facultyApplicationStatusEnum,
  facultyApplicationsTable,
  facultyInvitationStatusEnum,
  facultyInvitationsTable,
  facultyMembershipsTable,
  facultyRoleEnum,
  facultyUsersTable,
  facultyVoiceProfilesTable,
  gapDiscoveryEventsTable,
  institutionAgreementsTable,
  interpretationChunksTable,
  interpretationCommentsTable,
  interpretationOriginEnum,
  interpretationsTable,
  interpretationStatusEnum,
  interpretationVersionsTable,
  knowledgeRelationsTable,
  knowledgeRelationTypeEnum,
  knowledgeVersionChunksTable,
  knowledgeVersionChunkKindEnum,
  knowledgeVersionsTable,
  pillarResourcesTable,
  pillarsTable,
  queryClustersTable,
  researchDiscoveryCandidateStatusEnum,
  researchDiscoveryCandidatesTable,
  researchDiscoveryRunStatusEnum,
  researchDiscoveryRunsTable,
  rubricCheckResultsTable,
  rubricChecksTable,
  slmAnswerLinksTable,
  sourceAssessmentStatusEnum,
  sourceAuditLogTable,
  sourceChunksTable,
  sourceKindEnum,
  sourceRetentionStatusEnum,
  sourceRightsBasisEnum,
  sourcesTable,
  sourceStatusEnum,
  sourceVersionsTable,
  uncoveredEscalationsTable,
  visitorSessionsTable,
  voiceProfileSourceEnum,
};

/** Drizzle-compatible schema object containing only the bounded context. */
export const slmSchema = {
  adviceGuardTermsTable,
  agentQueriesTable,
  consumerAccountsTable,
  consumerLoginTokensTable,
  crawlCandidateStatusEnum,
  crawlCandidatesTable,
  crawlRunStatusEnum,
  crawlRunsTable,
  evalGradingsTable,
  evalItemsTable,
  evalRunsTable,
  emailRateLimitHitsTable,
  expectedOutcomeEnum,
  facultyApplicationStatusEnum,
  facultyApplicationsTable,
  facultyInvitationStatusEnum,
  facultyInvitationsTable,
  facultyMembershipsTable,
  facultyRoleEnum,
  facultyUsersTable,
  facultyVoiceProfilesTable,
  gapDiscoveryEventsTable,
  institutionAgreementsTable,
  interpretationChunksTable,
  interpretationCommentsTable,
  interpretationOriginEnum,
  interpretationsTable,
  interpretationStatusEnum,
  interpretationVersionsTable,
  knowledgeRelationsTable,
  knowledgeRelationTypeEnum,
  knowledgeVersionChunksTable,
  knowledgeVersionChunkKindEnum,
  knowledgeVersionsTable,
  pillarResourcesTable,
  pillarsTable,
  queryClustersTable,
  researchDiscoveryCandidateStatusEnum,
  researchDiscoveryCandidatesTable,
  researchDiscoveryRunStatusEnum,
  researchDiscoveryRunsTable,
  rubricCheckResultsTable,
  rubricChecksTable,
  slmAnswerLinksTable,
  sourceAssessmentStatusEnum,
  sourceAuditLogTable,
  sourceChunksTable,
  sourceKindEnum,
  sourceRetentionStatusEnum,
  sourceRightsBasisEnum,
  sourcesTable,
  sourceStatusEnum,
  sourceVersionsTable,
  uncoveredEscalationsTable,
  visitorSessionsTable,
  voiceProfileSourceEnum,
} as const;

/**
 * Review-friendly, dependency-free description of the allowlist. Physical
 * table names are repeated deliberately so boundary reviews do not need to
 * evaluate Drizzle objects.
 */
export const slmSchemaManifest = {
  modules: [
    "faculty",
    "sources",
    "interpretations",
    "knowledge",
    "agentQueries",
    "adviceGuard",
    "crawls",
    "consumers",
    "emailRateLimit",
    "gapDiscovery",
    "pillarResources",
    "slmAnswerLinks",
    "stewardVoice",
    "uncoveredEscalations",
    "visitorSessions",
    "evals",
  ],
  tables: [
    "pillars",
    "faculty_users",
    "faculty_memberships",
    "faculty_invitations",
    "faculty_applications",
    "institution_agreements",
    "sources",
    "source_chunks",
    "source_versions",
    "source_audit_log",
    "interpretations",
    "interpretation_versions",
    "interpretation_comments",
    "interpretation_chunks",
    "rubric_checks",
    "rubric_check_results",
    "knowledge_relations",
    "knowledge_versions",
    "knowledge_version_chunks",
    "agent_queries",
    "query_clusters",
    "crawl_runs",
    "crawl_candidates",
    "research_discovery_runs",
    "research_discovery_candidates",
    "gap_discovery_events",
    "faculty_voice_profiles",
    "eval_runs",
    "eval_items",
    "eval_gradings",
    "advice_guard_terms",
    "pillar_resources",
    "slm_answer_links",
    "uncovered_escalations",
    "consumer_accounts",
    "consumer_login_tokens",
    "visitor_sessions",
    "email_rate_limit_hits",
  ],
  enums: [
    "faculty_role",
    "faculty_invitation_status",
    "faculty_application_status",
    "source_kind",
    "source_status",
    "source_rights_basis",
    "source_retention_status",
    "source_assessment_status",
    "interpretation_status",
    "interpretation_origin",
    "knowledge_relation_type",
    "knowledge_version_chunk_kind",
    "crawl_run_status",
    "crawl_candidate_status",
    "research_discovery_run_status",
    "research_discovery_candidate_status",
    "voice_profile_source",
    "eval_expected_outcome",
  ],
} as const;
